// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Do NOT commit real keys. Generate this file locally by running:
///   dart run flutterfire_cli:flutterfire configure
///
/// See lib/firebase_options.example.dart for structure.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_ME_RUN_FLUTTERFIRE_CONFIGURE',
    appId: 'REPLACE_ME_RUN_FLUTTERFIRE_CONFIGURE',
    messagingSenderId: 'REPLACE_ME_RUN_FLUTTERFIRE_CONFIGURE',
    projectId: 'comprehensiveislamic',
    authDomain: 'comprehensiveislamic.firebaseapp.com',
    storageBucket: 'comprehensiveislamic.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_ME_RUN_FLUTTERFIRE_CONFIGURE',
    appId: 'REPLACE_ME_RUN_FLUTTERFIRE_CONFIGURE',
    messagingSenderId: 'REPLACE_ME_RUN_FLUTTERFIRE_CONFIGURE',
    projectId: 'comprehensiveislamic',
    storageBucket: 'comprehensiveislamic.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME_RUN_FLUTTERFIRE_CONFIGURE',
    appId: 'REPLACE_ME_RUN_FLUTTERFIRE_CONFIGURE',
    messagingSenderId: 'REPLACE_ME_RUN_FLUTTERFIRE_CONFIGURE',
    projectId: 'comprehensiveislamic',
    storageBucket: 'comprehensiveislamic.firebasestorage.app',
    iosBundleId: 'com.example.comprehensiveIslamicApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_ME_RUN_FLUTTERFIRE_CONFIGURE',
    appId: 'REPLACE_ME_RUN_FLUTTERFIRE_CONFIGURE',
    messagingSenderId: 'REPLACE_ME_RUN_FLUTTERFIRE_CONFIGURE',
    projectId: 'comprehensiveislamic',
    storageBucket: 'comprehensiveislamic.firebasestorage.app',
    iosBundleId: 'com.example.comprehensiveIslamicApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REPLACE_ME_RUN_FLUTTERFIRE_CONFIGURE',
    appId: 'REPLACE_ME_RUN_FLUTTERFIRE_CONFIGURE',
    messagingSenderId: 'REPLACE_ME_RUN_FLUTTERFIRE_CONFIGURE',
    projectId: 'comprehensiveislamic',
    authDomain: 'comprehensiveislamic.firebaseapp.com',
    storageBucket: 'comprehensiveislamic.firebasestorage.app',
  );
}
