// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv-IiGa70loo5nuCMEazyvNCewoVUmT6k',
    appId: '1:468419636460:web:e53c8bfb85c1460da0c9c9',
    messagingSenderId: '468419636460',
    projectId: 'comprehensiveislamic',
    authDomain: 'comprehensiveislamic.firebaseapp.com',
    storageBucket: 'comprehensiveislamic.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfZEJqtS9AH_18Gd5sOl3X6v8_4WGZ6vk',
    appId: '1:468419636460:android:c9e9867d39a432d8a0c9c9',
    messagingSenderId: '468419636460',
    projectId: 'comprehensiveislamic',
    storageBucket: 'comprehensiveislamic.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7bbkOPOsb1eYoS5ixGm1yTwY_puzWmbU',
    appId: '1:468419636460:ios:334bc8b59b8c9b1fa0c9c9',
    messagingSenderId: '468419636460',
    projectId: 'comprehensiveislamic',
    storageBucket: 'comprehensiveislamic.firebasestorage.app',
    iosBundleId: 'com.example.comprehensiveIslamicApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7bbkOPOsb1eYoS5ixGm1yTwY_puzWmbU',
    appId: '1:468419636460:ios:334bc8b59b8c9b1fa0c9c9',
    messagingSenderId: '468419636460',
    projectId: 'comprehensiveislamic',
    storageBucket: 'comprehensiveislamic.firebasestorage.app',
    iosBundleId: 'com.example.comprehensiveIslamicApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv-IiGa70loo5nuCMEazyvNCewoVUmT6k',
    appId: '1:468419636460:web:7e3607d53c135d6da0c9c9',
    messagingSenderId: '468419636460',
    projectId: 'comprehensiveislamic',
    authDomain: 'comprehensiveislamic.firebaseapp.com',
    storageBucket: 'comprehensiveislamic.firebasestorage.app',
  );
}
